### PR TITLE
Toc tos

### PR DESCRIPTION
**Pull request by deetz99**
issues: #46 #59 

- initial terms of service page
- fix some darkmode colours
- move mobile menu to app.vue level
- create table of contents with intersection observer for docs page
- add previous/next buttons for docs page
- refactor layouts to keep header, aside and table of contents fixed

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://apigw-dev--pr-60-c7vynk3q.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://apigw-dev--pr-60-c7vynk3q.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
